version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - st_backend

  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    volumes:
      - shared-volume:/opt/selenium
    ports:
      - "4444:4444"
    networks:
      - st_backend

  web_crawler:
    image: web_crawler
    container_name: web_crawler
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/stocks
      SELENIUM_URL: http://selenium-chrome:4444/wd/hub
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - shared-volume:/opt/selenium
    depends_on:
      - mongodb
      - selenium-chrome
    networks:
      - st_backend
    ports:
      - "8080:8080"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - st_backend

  stock:
    image: stock
    container_name: stock
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/stocks
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      FILE_PATH_DOCKER: /app/data
    depends_on:
      - mongodb
      - redis
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
      - st_backend

  data_analysis:
    image: data_analysis
    container_name: data_analysis
    depends_on:
      - stock
    networks:
      - st_backend
    ports:
      - "8082:8082"

networks:
  st_backend:
    driver: bridge

volumes:
  mongodb-data:
  shared-volume: