server:
  address: 0.0.0.0
  port: 8081

grpc:
  server:
    port: 50051

spring:
  application:
    name: stock

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/stocks}

  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path=/swagger-ui:html
